timeout: "1800s"
steps:

- name: gcr.io/cloud-builders/git
  args: ['clone', '-b', '$BRANCH_NAME', '--recurse-submodules', '-v', 'https://github.com/wortheumio/wortheum.git']
  id: "Git clone"

- name: gcr.io/cloud-builders/git
  dir: "wortheum"
  args: ['status']
  id: "Git status"

- name: 'gcr.io/cloud-builders/docker'
  dir: "wortheum"
  args: [
      'build',
      '-f', '../Builder.DockerFile',
      '.'
      ]
options:
  machineType: 'N1_HIGHCPU_32'

