#include <worth/protocol/get_config.hpp>
#include <worth/protocol/config.hpp>
#include <worth/protocol/asset.hpp>
#include <worth/protocol/types.hpp>
#include <worth/protocol/version.hpp>

namespace worth { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_NET
   result[ "IS_TEST_NET" ] = true;
   result["TESTNET_BLOCK_LIMIT"] = TESTNET_BLOCK_LIMIT;
#else
   result[ "IS_TEST_NET" ] = false;
#endif
#ifdef WORTHEUM_ENABLE_WMT
   result[ "WORTHEUM_ENABLE_WMT" ] = true;
   result["WMT_MAX_VOTABLE_ASSETS"] = WMT_MAX_VOTABLE_ASSETS;
   result["WMT_VESTING_WITHDRAW_INTERVAL_SECONDS"] = WMT_VESTING_WITHDRAW_INTERVAL_SECONDS;
   result["WMT_UPVOTE_LOCKOUT"] = WMT_UPVOTE_LOCKOUT;
   result["WMT_EMISSION_MIN_INTERVAL_SECONDS"] = WMT_EMISSION_MIN_INTERVAL_SECONDS;
   result["WMT_EMIT_INDEFINITELY"] = WMT_EMIT_INDEFINITELY;
   result["WMT_MAX_NOMINAL_VOTES_PER_DAY"] = WMT_MAX_NOMINAL_VOTES_PER_DAY;
   result["WMT_MAX_VOTES_PER_REGENERATION"] = WMT_MAX_VOTES_PER_REGENERATION;
   result["WMT_DEFAULT_VOTES_PER_REGEN_PERIOD"] = WMT_DEFAULT_VOTES_PER_REGEN_PERIOD;
   result["WMT_DEFAULT_PERCENT_CURATION_REWARDS"] = WMT_DEFAULT_PERCENT_CURATION_REWARDS;
#else
   result[ "WORTHEUM_ENABLE_WMT" ] = false;
#endif

   result["WBD_SYMBOL"] = WBD_SYMBOL;
   result["WORTH_INITIAL_VOTE_POWER_RATE"] = WORTH_INITIAL_VOTE_POWER_RATE;
   result["WORTH_REDUCED_VOTE_POWER_RATE"] = WORTH_REDUCED_VOTE_POWER_RATE;
   result["WORTH_100_PERCENT"] = WORTH_100_PERCENT;
   result["WORTH_1_PERCENT"] = WORTH_1_PERCENT;
   result["WORTH_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = WORTH_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["WORTH_ACTIVE_CHALLENGE_COOLDOWN"] = WORTH_ACTIVE_CHALLENGE_COOLDOWN;
   result["WORTH_ACTIVE_CHALLENGE_FEE"] = WORTH_ACTIVE_CHALLENGE_FEE;
   result["WORTH_ADDRESS_PREFIX"] = WORTH_ADDRESS_PREFIX;
   result["WORTH_APR_PERCENT_MULTIPLY_PER_BLOCK"] = WORTH_APR_PERCENT_MULTIPLY_PER_BLOCK;
   result["WORTH_APR_PERCENT_MULTIPLY_PER_HOUR"] = WORTH_APR_PERCENT_MULTIPLY_PER_HOUR;
   result["WORTH_APR_PERCENT_MULTIPLY_PER_ROUND"] = WORTH_APR_PERCENT_MULTIPLY_PER_ROUND;
   result["WORTH_APR_PERCENT_SHIFT_PER_BLOCK"] = WORTH_APR_PERCENT_SHIFT_PER_BLOCK;
   result["WORTH_APR_PERCENT_SHIFT_PER_HOUR"] = WORTH_APR_PERCENT_SHIFT_PER_HOUR;
   result["WORTH_APR_PERCENT_SHIFT_PER_ROUND"] = WORTH_APR_PERCENT_SHIFT_PER_ROUND;
   result["WORTH_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = WORTH_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["WORTH_BANDWIDTH_PRECISION"] = WORTH_BANDWIDTH_PRECISION;
   result["WORTH_BENEFICIARY_LIMIT"] = WORTH_BENEFICIARY_LIMIT;
   result["WORTH_BLOCKCHAIN_PRECISION"] = WORTH_BLOCKCHAIN_PRECISION;
   result["WORTH_BLOCKCHAIN_PRECISION_DIGITS"] = WORTH_BLOCKCHAIN_PRECISION_DIGITS;
   result["WORTH_BLOCKCHAIN_HARDFORK_VERSION"] = WORTH_BLOCKCHAIN_HARDFORK_VERSION;
   result["WORTH_BLOCKCHAIN_VERSION"] = WORTH_BLOCKCHAIN_VERSION;
   result["WORTH_BLOCK_INTERVAL"] = WORTH_BLOCK_INTERVAL;
   result["WORTH_BLOCKS_PER_DAY"] = WORTH_BLOCKS_PER_DAY;
   result["WORTH_BLOCKS_PER_HOUR"] = WORTH_BLOCKS_PER_HOUR;
   result["WORTH_BLOCKS_PER_YEAR"] = WORTH_BLOCKS_PER_YEAR;
   result["WORTH_CASHOUT_WINDOW_SECONDS"] = WORTH_CASHOUT_WINDOW_SECONDS;
   result["WORTH_CASHOUT_WINDOW_SECONDS_PRE_HF12"] = WORTH_CASHOUT_WINDOW_SECONDS_PRE_HF12;
   result["WORTH_CASHOUT_WINDOW_SECONDS_PRE_HF17"] = WORTH_CASHOUT_WINDOW_SECONDS_PRE_HF17;
   result["WORTH_CHAIN_ID"] = WORTH_CHAIN_ID;
   result["WORTH_COMMENT_REWARD_FUND_NAME"] = WORTH_COMMENT_REWARD_FUND_NAME;
   result["WORTH_COMMENT_TITLE_LIMIT"] = WORTH_COMMENT_TITLE_LIMIT;
   result["WORTH_CONTENT_APR_PERCENT"] = WORTH_CONTENT_APR_PERCENT;
   result["WORTH_CONTENT_CONSTANT_HF0"] = WORTH_CONTENT_CONSTANT_HF0;
   result["WORTH_CONTENT_CONSTANT_HF21"] = WORTH_CONTENT_CONSTANT_HF21;
   result["WORTH_CONTENT_REWARD_PERCENT_HF16"] = WORTH_CONTENT_REWARD_PERCENT_HF16;
   result["WORTH_CONTENT_REWARD_PERCENT_HF21"] = WORTH_CONTENT_REWARD_PERCENT_HF21;
   result["WORTH_CONVERSION_DELAY"] = WORTH_CONVERSION_DELAY;
   result["WORTH_CONVERSION_DELAY_PRE_HF_16"] = WORTH_CONVERSION_DELAY_PRE_HF_16;
   result["WORTH_CREATE_ACCOUNT_DELEGATION_RATIO"] = WORTH_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["WORTH_CREATE_ACCOUNT_DELEGATION_TIME"] = WORTH_CREATE_ACCOUNT_DELEGATION_TIME;
   result["WORTH_CREATE_ACCOUNT_WITH_WORTH_MODIFIER"] = WORTH_CREATE_ACCOUNT_WITH_WORTH_MODIFIER;
   result["WORTH_CURATE_APR_PERCENT"] = WORTH_CURATE_APR_PERCENT;
   result["WORTH_CUSTOM_OP_DATA_MAX_LENGTH"] = WORTH_CUSTOM_OP_DATA_MAX_LENGTH;
   result["WORTH_CUSTOM_OP_ID_MAX_LENGTH"] = WORTH_CUSTOM_OP_ID_MAX_LENGTH;
   result["WORTH_DEFAULT_WBD_INTEREST_RATE"] = WORTH_DEFAULT_WBD_INTEREST_RATE;
   result["WORTH_DOWNVOTE_POOL_PERCENT_HF21"] = WORTH_DOWNVOTE_POOL_PERCENT_HF21;
   result["WORTH_EQUIHASH_K"] = WORTH_EQUIHASH_K;
   result["WORTH_EQUIHASH_N"] = WORTH_EQUIHASH_N;
   result["WORTH_FEED_HISTORY_WINDOW"] = WORTH_FEED_HISTORY_WINDOW;
   result["WORTH_FEED_HISTORY_WINDOW_PRE_HF_16"] = WORTH_FEED_HISTORY_WINDOW_PRE_HF_16;
   result["WORTH_FEED_INTERVAL_BLOCKS"] = WORTH_FEED_INTERVAL_BLOCKS;
   result["WORTH_GENESIS_TIME"] = WORTH_GENESIS_TIME;
   result["WORTH_HARDFORK_REQUIRED_WITNESSES"] = WORTH_HARDFORK_REQUIRED_WITNESSES;
   result["WORTH_HF21_CONVERGENT_LINEAR_RECENT_CLAIMS"] = WORTH_HF21_CONVERGENT_LINEAR_RECENT_CLAIMS;
   result["WORTH_INFLATION_NARROWING_PERIOD"] = WORTH_INFLATION_NARROWING_PERIOD;
   result["WORTH_INFLATION_RATE_START_PERCENT"] = WORTH_INFLATION_RATE_START_PERCENT;
   result["WORTH_INFLATION_RATE_STOP_PERCENT"] = WORTH_INFLATION_RATE_STOP_PERCENT;
   result["WORTH_INIT_MINER_NAME"] = WORTH_INIT_MINER_NAME;
   result["WORTH_INIT_PUBLIC_KEY_STR"] = WORTH_INIT_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["WORTH_INIT_PRIVATE_KEY"] = WORTH_INIT_PRIVATE_KEY;
#endif
   result["WORTH_INIT_SUPPLY"] = WORTH_INIT_SUPPLY;
   result["WORTH_WBD_INIT_SUPPLY"] = WORTH_WBD_INIT_SUPPLY;
   result["WORTH_INIT_TIME"] = WORTH_INIT_TIME;
   result["WORTH_IRREVERSIBLE_THRESHOLD"] = WORTH_IRREVERSIBLE_THRESHOLD;
   result["WORTH_LIQUIDITY_APR_PERCENT"] = WORTH_LIQUIDITY_APR_PERCENT;
   result["WORTH_LIQUIDITY_REWARD_BLOCKS"] = WORTH_LIQUIDITY_REWARD_BLOCKS;
   result["WORTH_LIQUIDITY_REWARD_PERIOD_SEC"] = WORTH_LIQUIDITY_REWARD_PERIOD_SEC;
   result["WORTH_LIQUIDITY_TIMEOUT_SEC"] = WORTH_LIQUIDITY_TIMEOUT_SEC;
   result["WORTH_MAX_ACCOUNT_CREATION_FEE"] = WORTH_MAX_ACCOUNT_CREATION_FEE;
   result["WORTH_MAX_ACCOUNT_NAME_LENGTH"] = WORTH_MAX_ACCOUNT_NAME_LENGTH;
   result["WORTH_MAX_ACCOUNT_WITNESS_VOTES"] = WORTH_MAX_ACCOUNT_WITNESS_VOTES;
   result["WORTH_MAX_ASSET_WHITELIST_AUTHORITIES"] = WORTH_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["WORTH_MAX_AUTHORITY_MEMBERSHIP"] = WORTH_MAX_AUTHORITY_MEMBERSHIP;
   result["WORTH_MAX_BLOCK_SIZE"] = WORTH_MAX_BLOCK_SIZE;
   result["WORTH_SOFT_MAX_BLOCK_SIZE"] = WORTH_SOFT_MAX_BLOCK_SIZE;
   result["WORTH_MAX_CASHOUT_WINDOW_SECONDS"] = WORTH_MAX_CASHOUT_WINDOW_SECONDS;
   result["WORTH_MAX_COMMENT_DEPTH"] = WORTH_MAX_COMMENT_DEPTH;
   result["WORTH_MAX_COMMENT_DEPTH_PRE_HF17"] = WORTH_MAX_COMMENT_DEPTH_PRE_HF17;
   result["WORTH_MAX_FEED_AGE_SECONDS"] = WORTH_MAX_FEED_AGE_SECONDS;
   result["WORTH_MAX_INSTANCE_ID"] = WORTH_MAX_INSTANCE_ID;
   result["WORTH_MAX_MEMO_SIZE"] = WORTH_MAX_MEMO_SIZE;
   result["WORTH_MAX_WITNESSES"] = WORTH_MAX_WITNESSES;
   result["WORTH_MAX_MINER_WITNESSES_HF0"] = WORTH_MAX_MINER_WITNESSES_HF0;
   result["WORTH_MAX_MINER_WITNESSES_HF17"] = WORTH_MAX_MINER_WITNESSES_HF17;
   result["WORTH_MAX_PERMLINK_LENGTH"] = WORTH_MAX_PERMLINK_LENGTH;
   result["WORTH_MAX_PROXY_RECURSION_DEPTH"] = WORTH_MAX_PROXY_RECURSION_DEPTH;
   result["WORTH_MAX_RATION_DECAY_RATE"] = WORTH_MAX_RATION_DECAY_RATE;
   result["WORTH_MAX_RESERVE_RATIO"] = WORTH_MAX_RESERVE_RATIO;
   result["WORTH_MAX_RUNNER_WITNESSES_HF0"] = WORTH_MAX_RUNNER_WITNESSES_HF0;
   result["WORTH_MAX_RUNNER_WITNESSES_HF17"] = WORTH_MAX_RUNNER_WITNESSES_HF17;
   result["WORTH_MAX_SATOSHIS"] = WORTH_MAX_SATOSHIS;
   result["WORTH_MAX_SHARE_SUPPLY"] = WORTH_MAX_SHARE_SUPPLY;
   result["WORTH_MAX_SIG_CHECK_DEPTH"] = WORTH_MAX_SIG_CHECK_DEPTH;
   result["WORTH_MAX_SIG_CHECK_ACCOUNTS"] = WORTH_MAX_SIG_CHECK_ACCOUNTS;
   result["WORTH_MAX_TIME_UNTIL_EXPIRATION"] = WORTH_MAX_TIME_UNTIL_EXPIRATION;
   result["WORTH_MAX_TRANSACTION_SIZE"] = WORTH_MAX_TRANSACTION_SIZE;
   result["WORTH_MAX_UNDO_HISTORY"] = WORTH_MAX_UNDO_HISTORY;
   result["WORTH_MAX_URL_LENGTH"] = WORTH_MAX_URL_LENGTH;
   result["WORTH_MAX_VOTE_CHANGES"] = WORTH_MAX_VOTE_CHANGES;
   result["WORTH_MAX_VOTED_WITNESSES_HF0"] = WORTH_MAX_VOTED_WITNESSES_HF0;
   result["WORTH_MAX_VOTED_WITNESSES_HF17"] = WORTH_MAX_VOTED_WITNESSES_HF17;
   result["WORTH_MAX_WITHDRAW_ROUTES"] = WORTH_MAX_WITHDRAW_ROUTES;
   result["WORTH_MAX_WITNESS_URL_LENGTH"] = WORTH_MAX_WITNESS_URL_LENGTH;
   result["WORTH_MIN_ACCOUNT_CREATION_FEE"] = WORTH_MIN_ACCOUNT_CREATION_FEE;
   result["WORTH_MIN_ACCOUNT_NAME_LENGTH"] = WORTH_MIN_ACCOUNT_NAME_LENGTH;
   result["WORTH_MIN_BLOCK_SIZE_LIMIT"] = WORTH_MIN_BLOCK_SIZE_LIMIT;
   result["WORTH_MIN_BLOCK_SIZE"] = WORTH_MIN_BLOCK_SIZE;
   result["WORTH_MIN_CONTENT_REWARD"] = WORTH_MIN_CONTENT_REWARD;
   result["WORTH_MIN_CURATE_REWARD"] = WORTH_MIN_CURATE_REWARD;
   result["WORTH_MIN_PERMLINK_LENGTH"] = WORTH_MIN_PERMLINK_LENGTH;
   result["WORTH_MIN_REPLY_INTERVAL"] = WORTH_MIN_REPLY_INTERVAL;
   result["WORTH_MIN_REPLY_INTERVAL_HF20"] = WORTH_MIN_REPLY_INTERVAL_HF20;
   result["WORTH_MIN_ROOT_COMMENT_INTERVAL"] = WORTH_MIN_ROOT_COMMENT_INTERVAL;
   result["WORTH_MIN_COMMENT_EDIT_INTERVAL"] = WORTH_MIN_COMMENT_EDIT_INTERVAL;
   result["WORTH_MIN_VOTE_INTERVAL_SEC"] = WORTH_MIN_VOTE_INTERVAL_SEC;
   result["WORTH_MINER_ACCOUNT"] = WORTH_MINER_ACCOUNT;
   result["WORTH_MINER_PAY_PERCENT"] = WORTH_MINER_PAY_PERCENT;
   result["WORTH_MIN_FEEDS"] = WORTH_MIN_FEEDS;
   result["WORTH_MINING_REWARD"] = WORTH_MINING_REWARD;
   result["WORTH_MINING_TIME"] = WORTH_MINING_TIME;
   result["WORTH_MIN_LIQUIDITY_REWARD"] = WORTH_MIN_LIQUIDITY_REWARD;
   result["WORTH_MIN_LIQUIDITY_REWARD_PERIOD_SEC"] = WORTH_MIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["WORTH_MIN_PAYOUT_WBD"] = WORTH_MIN_PAYOUT_WBD;
   result["WORTH_MIN_POW_REWARD"] = WORTH_MIN_POW_REWARD;
   result["WORTH_MIN_PRODUCER_REWARD"] = WORTH_MIN_PRODUCER_REWARD;
   result["WORTH_MIN_TRANSACTION_EXPIRATION_LIMIT"] = WORTH_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["WORTH_MIN_TRANSACTION_SIZE_LIMIT"] = WORTH_MIN_TRANSACTION_SIZE_LIMIT;
   result["WORTH_MIN_UNDO_HISTORY"] = WORTH_MIN_UNDO_HISTORY;
   result["WORTH_NULL_ACCOUNT"] = WORTH_NULL_ACCOUNT;
   result["WORTH_NUM_INIT_MINERS"] = WORTH_NUM_INIT_MINERS;
   result["WORTH_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = WORTH_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["WORTH_OWNER_AUTH_RECOVERY_PERIOD"] = WORTH_OWNER_AUTH_RECOVERY_PERIOD;
   result["WORTH_OWNER_CHALLENGE_COOLDOWN"] = WORTH_OWNER_CHALLENGE_COOLDOWN;
   result["WORTH_OWNER_CHALLENGE_FEE"] = WORTH_OWNER_CHALLENGE_FEE;
   result["WORTH_OWNER_UPDATE_LIMIT"] = WORTH_OWNER_UPDATE_LIMIT;
   result["WORTH_POST_AVERAGE_WINDOW"] = WORTH_POST_AVERAGE_WINDOW;
   result["WORTH_POST_REWARD_FUND_NAME"] = WORTH_POST_REWARD_FUND_NAME;
   result["WORTH_POST_WEIGHT_CONSTANT"] = WORTH_POST_WEIGHT_CONSTANT;
   result["WORTH_POW_APR_PERCENT"] = WORTH_POW_APR_PERCENT;
   result["WORTH_PRODUCER_APR_PERCENT"] = WORTH_PRODUCER_APR_PERCENT;
   result["WORTH_PROXY_TO_SELF_ACCOUNT"] = WORTH_PROXY_TO_SELF_ACCOUNT;
   result["WORTH_WBD_INTEREST_COMPOUND_INTERVAL_SEC"] = WORTH_WBD_INTEREST_COMPOUND_INTERVAL_SEC;
   result["WORTH_SECONDS_PER_YEAR"] = WORTH_SECONDS_PER_YEAR;
   result["WORTH_PROPOSAL_FUND_PERCENT_HF0"] = WORTH_PROPOSAL_FUND_PERCENT_HF0;
   result["WORTH_PROPOSAL_FUND_PERCENT_HF21"] = WORTH_PROPOSAL_FUND_PERCENT_HF21;
   result["WORTH_RECENT_RSHARES_DECAY_TIME_HF19"] = WORTH_RECENT_RSHARES_DECAY_TIME_HF19;
   result["WORTH_RECENT_RSHARES_DECAY_TIME_HF17"] = WORTH_RECENT_RSHARES_DECAY_TIME_HF17;
   result["WORTH_REVERSE_AUCTION_WINDOW_SECONDS_HF6"] = WORTH_REVERSE_AUCTION_WINDOW_SECONDS_HF6;
   result["WORTH_REVERSE_AUCTION_WINDOW_SECONDS_HF20"] = WORTH_REVERSE_AUCTION_WINDOW_SECONDS_HF20;
   result["WORTH_REVERSE_AUCTION_WINDOW_SECONDS_HF21"] = WORTH_REVERSE_AUCTION_WINDOW_SECONDS_HF21;
   result["WORTH_ROOT_POST_PARENT"] = WORTH_ROOT_POST_PARENT;
   result["WORTH_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = WORTH_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["WORTH_SAVINGS_WITHDRAW_TIME"] = WORTH_SAVINGS_WITHDRAW_TIME;
   result["WORTH_WBD_START_PERCENT_HF14"] = WORTH_WBD_START_PERCENT_HF14;
   result["WORTH_WBD_START_PERCENT_HF20"] = WORTH_WBD_START_PERCENT_HF20;
   result["WORTH_WBD_STOP_PERCENT_HF14"] = WORTH_WBD_STOP_PERCENT_HF14;
   result["WORTH_WBD_STOP_PERCENT_HF20"] = WORTH_WBD_STOP_PERCENT_HF20;
   result["WORTH_SECOND_CASHOUT_WINDOW"] = WORTH_SECOND_CASHOUT_WINDOW;
   result["WORTH_SOFT_MAX_COMMENT_DEPTH"] = WORTH_SOFT_MAX_COMMENT_DEPTH;
   result["WORTH_START_MINER_VOTING_BLOCK"] = WORTH_START_MINER_VOTING_BLOCK;
   result["WORTH_START_VESTING_BLOCK"] = WORTH_START_VESTING_BLOCK;
   result["WORTH_TEMP_ACCOUNT"] = WORTH_TEMP_ACCOUNT;
   result["WORTH_UPVOTE_LOCKOUT_HF7"] = WORTH_UPVOTE_LOCKOUT_HF7;
   result["WORTH_UPVOTE_LOCKOUT_HF17"] = WORTH_UPVOTE_LOCKOUT_HF17;
   result["WORTH_UPVOTE_LOCKOUT_SECONDS"] = WORTH_UPVOTE_LOCKOUT_SECONDS;
   result["WORTH_VESTING_FUND_PERCENT_HF16"] = WORTH_VESTING_FUND_PERCENT_HF16;
   result["WORTH_VESTING_WITHDRAW_INTERVALS"] = WORTH_VESTING_WITHDRAW_INTERVALS;
   result["WORTH_VESTING_WITHDRAW_INTERVALS_PRE_HF_16"] = WORTH_VESTING_WITHDRAW_INTERVALS_PRE_HF_16;
   result["WORTH_VESTING_WITHDRAW_INTERVAL_SECONDS"] = WORTH_VESTING_WITHDRAW_INTERVAL_SECONDS;
   result["WORTH_VOTE_DUST_THRESHOLD"] = WORTH_VOTE_DUST_THRESHOLD;
   result["WORTH_VOTING_MANA_REGENERATION_SECONDS"] = WORTH_VOTING_MANA_REGENERATION_SECONDS;
   result["WORTH_SYMBOL"] = WORTH_SYMBOL;
   result["VESTS_SYMBOL"] = VESTS_SYMBOL;
   result["WORTH_VIRTUAL_SCHEDULE_LAP_LENGTH"] = WORTH_VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["WORTH_VIRTUAL_SCHEDULE_LAP_LENGTH2"] = WORTH_VIRTUAL_SCHEDULE_LAP_LENGTH2;
   result["WORTH_MAX_LIMIT_ORDER_EXPIRATION"] = WORTH_MAX_LIMIT_ORDER_EXPIRATION;
   result["WORTH_DELEGATION_RETURN_PERIOD_HF0"] = WORTH_DELEGATION_RETURN_PERIOD_HF0;
   result["WORTH_DELEGATION_RETURN_PERIOD_HF20"] = WORTH_DELEGATION_RETURN_PERIOD_HF20;
   result["WORTH_RD_MIN_DECAY_BITS"] = WORTH_RD_MIN_DECAY_BITS;
   result["WORTH_RD_MAX_DECAY_BITS"] = WORTH_RD_MAX_DECAY_BITS;
   result["WORTH_RD_DECAY_DENOM_SHIFT"] = WORTH_RD_DECAY_DENOM_SHIFT;
   result["WORTH_RD_MAX_POOL_BITS"] = WORTH_RD_MAX_POOL_BITS;
   result["WORTH_RD_MAX_BUDGET_1"] = WORTH_RD_MAX_BUDGET_1;
   result["WORTH_RD_MAX_BUDGET_2"] = WORTH_RD_MAX_BUDGET_2;
   result["WORTH_RD_MAX_BUDGET_3"] = WORTH_RD_MAX_BUDGET_3;
   result["WORTH_RD_MAX_BUDGET"] = WORTH_RD_MAX_BUDGET;
   result["WORTH_RD_MIN_DECAY"] = WORTH_RD_MIN_DECAY;
   result["WORTH_RD_MIN_BUDGET"] = WORTH_RD_MIN_BUDGET;
   result["WORTH_RD_MAX_DECAY"] = WORTH_RD_MAX_DECAY;
   result["WORTH_ACCOUNT_SUBSIDY_PRECISION"] = WORTH_ACCOUNT_SUBSIDY_PRECISION;
   result["WORTH_WITNESS_SUBSIDY_BUDGET_PERCENT"] = WORTH_WITNESS_SUBSIDY_BUDGET_PERCENT;
   result["WORTH_WITNESS_SUBSIDY_DECAY_PERCENT"] = WORTH_WITNESS_SUBSIDY_DECAY_PERCENT;
   result["WORTH_DEFAULT_ACCOUNT_SUBSIDY_DECAY"] = WORTH_DEFAULT_ACCOUNT_SUBSIDY_DECAY;
   result["WORTH_DEFAULT_ACCOUNT_SUBSIDY_BUDGET"] = WORTH_DEFAULT_ACCOUNT_SUBSIDY_BUDGET;
   result["WORTH_DECAY_BACKSTOP_PERCENT"] = WORTH_DECAY_BACKSTOP_PERCENT;
   result["WORTH_BLOCK_GENERATION_POSTPONED_TX_LIMIT"] = WORTH_BLOCK_GENERATION_POSTPONED_TX_LIMIT;
   result["WORTH_PENDING_TRANSACTION_EXECUTION_LIMIT"] = WORTH_PENDING_TRANSACTION_EXECUTION_LIMIT;
   result["WORTH_TREASURY_ACCOUNT"] = WORTH_TREASURY_ACCOUNT;
   result["WORTH_TREASURY_FEE"] = WORTH_TREASURY_FEE;
   result["WORTH_PROPOSAL_MAINTENANCE_PERIOD"] = WORTH_PROPOSAL_MAINTENANCE_PERIOD;
   result["WORTH_PROPOSAL_MAINTENANCE_CLEANUP"] = WORTH_PROPOSAL_MAINTENANCE_CLEANUP;
   result["WORTH_PROPOSAL_SUBJECT_MAX_LENGTH"] = WORTH_PROPOSAL_SUBJECT_MAX_LENGTH;
   result["WORTH_PROPOSAL_MAX_IDS_NUMBER"] = WORTH_PROPOSAL_MAX_IDS_NUMBER;

   return result;
}

} } // worth::protocol
